version: "3.7"

networks:
  traefik:
    external:
      name: traefik

services:
  nginx:
    networks:
      - default
      - traefik

  mariadb:
    volumes:
      - ./private/mysql:/var/lib/mysql # Use bind mount
