<?php

/**
 * @file
 */

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\node\NodeInterface;

/**
 * @file
 * Primary module hooks for ktpersonal module.
 */

/**
 * Implements hook_update_N().
 */
function ktpersonal_update_9001(&$sandbox) {
  $z = 0;

  throw new Exception();
}

// Function ktpersonal_page_top(array &$page_top) {
//
//  $node = \Drupal::routeMatch()->getParameter('node');
//
//  if ($node instanceof NodeInterface) {
//    $nid = $node->id();
//
//    $parent = $node->get('field_parent_resource')->getValue();
//
//
//
//    $nodes = \Drupal::entityTypeManager()
//      ->getStorage('node')
//      ->loadByProperties([
//        'field_parent_resource' => $parent[0]['target_id'],
//      ]);
//
//    /** @var NodeInterface $node */
//    foreach ($nodes as $node) {
//      $key_array = $node->get('title')->getValue();
//      $key = $key_array[0]['value'];
//      $node_id_array[$key] = $node->id();
// $node->getTitle()
// $node->toUrl()
//    }
//
//    foreach ($node_id_array as $key => $node_id) {
//      $options = ['absolute' => TRUE];
//      $url = Url::fromRoute('entity.node.canonical', ['node' => $node_id], $options);
//      $link = Link::fromTextAndUrl($key, $url);
//
//      $page_top['ktpersonal'][$node_id] = $link->toRenderable();
//
//    }
//  }
// }

/**
 * Implements hook_entity_view().
 */

/**
 * Implements hook_page_build().
 */
function ktpersonal_page_build(array &$page) {

  $node = \Drupal::routeMatch()->getParameter('node');

  if ($node instanceof NodeInterface) {
    $nid = $node->id();

    $parent = $node->get('field_parent_resource')->getValue();

    $nodes = \Drupal::entityTypeManager()
      ->getStorage('node')
      ->loadByProperties([
        'field_parent_resource' => $parent[0]['target_id'],
      ]);

    /** @var \Drupal\node\NodeInterface $node */
    foreach ($nodes as $node) {
      $key_array = $node->get('title')->getValue();
      $key = $key_array[0]['value'];
      $node_id_array[$key] = $node->id();
      // $node->getTitle()
      //      $node->toUrl()
    }

    foreach ($node_id_array as $key => $node_id) {
      $options = ['absolute' => TRUE];
      $url = Url::fromRoute('entity.node.canonical', ['node' => $node_id], $options);
      $link = Link::fromTextAndUrl($key, $url);

      $page['content'][$node_id] = $link->toRenderable();

    }
  }

}


//function ktpersonal_form_alter(&$form, FormStateInterface $form_state, $form_id) {
//  $z = 0;
//
//  if ('ktpersonal_ktpersonal_build' == $form_id) {
//    $element = [
//      '#type' => 'container',
//      '#markup' => 'ololol ' . $form_id,
//      '#weight' => -100,
//    ];
//
//    $form['element'] = $element;
//  }
//}

/**
 *
 */
function ktpersonal_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  $routename = $route_match->getRouteName();

  if ('ktpersonal.ktpersonal_build' == $routename || 'ktpersonal.ktpersonal' == $routename) {

    $url = new Url('ktpersonal.ktpersonal');
    $link = new Link('Особистий кабінет', $url);

    // Add new link.
    $breadcrumb->addLink($link);
    // Saving the original links and caching.
    $original_links = $breadcrumb->getLinks();
    $cacheability = CacheableMetadata::createFromObject($breadcrumb);

    if ('ktpersonal.ktpersonal_build' == $routename) {
      unset($original_links[1]);
    }

    $breadcrumb = new Breadcrumb();
    $breadcrumb->setLinks($original_links);
    $breadcrumb->addCacheableDependency($cacheability);
  }
}

